# Generated by Django 3.1.6 on 2021-04-16 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_post__id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='_id',
            new_name='id',
        ),
    ]
